### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Hwkeyez** [backslash/ScryptRansomware#1]
Make a version where it just encrypts the files (no gui or readme)

The readme doesn't have anything in it and the decryptor doesn't work when compiling to windows :/

or make the notification gui not fullscreen and you can enter in the key sent on discord straight into it

and PLEASE make nothing show up until the files are encrypted!

**Comment by backslash** [comment]
**Make a version where it just encrypts the files (no gui or readme):**
Yah I can do that and create a separate folder for it.
**The readme doesn't have anything in it **
- Ill investigate this issue, it should work however its possible that its something simple like not closing the file handle.
**and the decryptor doesn't work when compiling to windows :/**
The decryptor was something I tossed together quickly, it does work however**** you should not be using it as a standalone seeing as you need to modify the key within it. Ill be working on adding a gui. 
**and PLEASE make nothing show up until the files are encrypted!**
This can be down however at the moment its running encryption in the background with multiple threads. It will go invisible once the person has clicked continue, **IT IS STILL RUNNING**, if you wanted to fix it your main fail would need to call your ransomware class beforehand:
`decrypter("YOHrdYmaYWgzmsQJsUHWLaIjytRMjlZN", "C:\\Users\\")`
The first part in our function is the encryption key and the second part is the folder in which you want it to iterate through. I'll fix up the decryptor on thursday and add a proper gui, I will also investigate the readme issue. Thank you!
